apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: test-analysis
  namespace: ray-infra
spec:
  metrics:
  - name: test-analysis
    interval: 5s
    count: 5
    successCondition: result == true
    failureLimit: 3
    provider:
      web:
        url: https://cat-fact.herokuapp.com/facts/58e00b5f0aac31001185ed24
        jsonPath: "{$.status.verified}"