apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: kuberay-operator
  releaseName: kuberay-operator
  repo: https://ray-project.github.io/kuberay-helm/
  version: 1.1.0
  includeCRDs: false