# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/argoproj.io/applicationset_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ray-operator-crds
  namespace: argocd
spec:
  generators:
    - list:
        elements:
        - stage: dev
          server: https://192.168.1.12
        - stage: stage
          server: https://192.168.1.13
        - stage: prod
          server: https://kubernetes.default.svc
  template: 
    metadata: 
      name: ray-operator-crds-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: ray-operator-crds:{{stage}}
    spec: 
      project: default
      source: 
        repoURL: https://github.com/ray-project/kuberay
        targetRevision: v1.2.2
        path: helm-chart/kuberay-operator/crds
      destination: 
        server: '{{server}}'
        namespace: ray
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Replace=true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/argoproj.io/applicationset_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ray-operator
  namespace: argocd
spec:
  generators:
    - list:
        elements:
        - stage: dev
          server: https://192.168.1.12
        - stage: stage
          server: https://192.168.1.13
        - stage: prod
          server: https://kubernetes.default.svc
  template: 
    metadata: 
      name: ray-operator-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: ray-infra:{{stage}}
    spec: 
      project: default
      source: 
        repoURL: https://github.com/han-steve/kargo-demo
        targetRevision: stage/{{stage}}
        path: ./apps/ray
      destination: 
        server: '{{server}}'
        namespace: ray
      syncPolicy:
        syncOptions:
          - CreateNamespace=true